<a href="https://colab.research.google.com/github/Saifsk06/Saif_Data_Analyst/blob/main/NumPy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy in Python**



In [ ]:
import numpy
import numpy as np

In [ ]:
a = numpy.array([10,12,23,34,45,56])
print(a)

[10 12 23 34 45 56]


In [ ]:
a = np.array([10,12,23,34,45])
print(a)

[10 12 23 34 45]


In [ ]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


**0 Dimension Array**

In [ ]:
import numpy as np
b = np.array(700)
print(b)
print(b.ndim)  #Check the number of dimension

700
0


**1 Dimension Array**

In [ ]:
c = np.array([23,43,55,64,78])
print(c)
print(c.ndim) #Check the number of dimension

[23 43 55 64 78]
1


**2 Dimension Array**


In [ ]:
d = np.array([[11,22,33],[44,55,66]])
print(d)
print(d.ndim)  #Check the number of dimension

[[11 22 33]
 [44 55 66]]
2


**3 Dimension Array**

In [ ]:
e = np.array([[[11,22,33,],[44,55,66],[77,88,99]]])
print(e)
print(e.ndim)  #Check the number of dimension

[[[11 22 33]
  [44 55 66]
  [77 88 99]]]
3


***Higher Dimension Arrays***

In [ ]:
e = np.array([12,24,36,48],ndmin=5)
print(e)

[[[[[12 24 36 48]]]]]


In [ ]:
e = np.array([12,24,36,48,60,72,84])
print(e[5]+[3])

[75]


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[7])

96


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[5]-[3])

[69]


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[5]*e[3])

3456


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[2]*[2])

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[7]/[2])

[48.]


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[6]**[3])

[592704]


In [ ]:
e = np.array([12,24,36,48,60,72,84,96,108])
print(e[7]//e[4])

1


In [ ]:
import numpy as np
a = np.array([12,24,36,48,60,72,84,96,108])
print(a[::2])

[ 12  36  60  84 108]


In [ ]:
a = np.array([12,24,36,48,60,72,84,96,108])
print(a[1::2])

[24 48 72 96]


In [ ]:
import numpy as np
c = np.array([[[9,8],[7,6],[1,2],[5,6]],[[2,3],[10,12],[5,4],[3,2]]])
print(c[0,0,1])

8


In [ ]:
c = np.array([[[9,8],[7,6],[1,2],[5,6]],[[2,3],[10,12],[5,4],[3,2]]])
print(c[1,1,1])

12


In [ ]:
e = np.array([[13,26,39,40,52],[76,57,48,39,100]])
print(e[0,1])

26


In [ ]:
e = np.array([[13,26,39,40,52],[76,57,48,39,100]])
print(e[1,4])

100


In [ ]:
e = np.array([[13,26,39,40,52],[76,57,48,39,100]])
print(e[1,2])

48


In [ ]:
f = np.array([1,2,3,4,5,6,7,8,9])
print(f[1:6])

[2 3 4 5 6]


In [ ]:
print(f[3:])

[4 5 6 7 8 9]


In [ ]:
f = np.array([1,2,3,4,5,6,7,8,9])
print(f[:3])

[1 2 3]


In [ ]:
f = np.array([1,2,3,4,5,6,7,8,9])
print(f[-4:])

[6 7 8 9]


In [ ]:
print(f[1:5:2])

[2 4]


In [ ]:
print(f[1::2])

[2 4 6 8]


In [ ]:
r = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
print(r[1,1:4])

[7 8 9]


In [ ]:
print(r[0:2,2])

[3 8]


In [ ]:
print(r[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([9,12,24,34,56])
x = arr.copy()
arr[0] = 42
print(arr)

[42 12 24 34 56]


In [ ]:
import numpy as np
z = np.array([10,12,13,14,15])
x = z.copy()
z[0] = 11
print(z)

[11 12 13 14 15]


In [ ]:
a = np.array([2,4,6,8,10,12])
x = a.copy()
a[2] = 100
print(a)

[  9  12 100  34  56]


In [ ]:
b = np.array([1, 2, 3, 4, 5])
x = b.copy()
y = b.view()
print(x.base)
print(y.base)

None
[ 9 12 24 34 56]


In [ ]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(c.shape)

(2, 4)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
d = np.array([11,12,13,14,15,16])
n = d.reshape(2,3)
print(n)

[[11 12 13]
 [14 15 16]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [ ]:
e = np.array([1,5,9])
for x in e:
  print(x)

1
5
9


In [ ]:
arr1 = np.array([[2,4],[6,8]])
arr2 = np.array([[10,12],[14,16]])
a = np.concatenate((arr1, arr2),axis = 1)
print(a)

[[ 2  4 10 12]
 [ 6  8 14 16]]


In [ ]:
import numpy as np
q = np.array([1,2,3,4,5,6])
x = np.array_split(q, 3)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
x = np.array([1, 2,3,4,4,4,6,4])
z = np.where(x == 4)
print(z)

(array([3, 4, 5, 7]),)


In [ ]:
import numpy as np
e = np.array([5,2,0,1,3,4])
print(np.sort(e))


[0 1 2 3 4 5]


In [ ]:
#LCM of numbers:
def calculate_lcm(num1,num2):
    if num1 > num2:
        greater = num1
    else:
        greater = num2
    while(True):
        if(greater % num1==0) and (greater % num2==0):
            lcm = greater
            break
    greater +=1
    return lcm

num1 = int(input("Enter number"))
num2 = int(input("Enter number"))
print("The L.C.M. of",num1,"and",num2,"is",calculate_lcm(num1,num2))

Enter number4
Enter number2
The L.C.M. of 4 and 2 is 4


In [ ]:
#LCM of numbers:
def calculate_hcf(num1,num2):
    if num1 > num2:
        smaller = num2
    else:
        smaller = num1
    for i in range(1,smaller+1):
      if((num1 % i==0)) and ((num2 % i==0)):
        hcf = i


num1 = int(input("Enter number"))
num2 = int(input("Enter number"))
print("The H.C.F. of",num1,"and",num2,"is",calculate_hcf(num1,num2))

Enter number8
Enter number12
The H.C.F. of 8 and 12 is None
